title: "AAAI 2025 Tutorial: The Lifecycle of Knowledge in Large Language Models: Memorization, Editing, and Beyond"
author: "Made by Jiateng Liu, Speakers: Manling Li, Zoey Li, Yuji Zhang, Chi Han, Heng Ji"
theme: minima
show_excerpts: true
